name = "labormed-vac"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "a8ce2608bda74d809930fdcec640b92c"
routes = [{ pattern = "vacina.labormed.app", custom_domain = true }]

# R2 bucket for static HTML
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "labormed-vac-storage"

[vars]
ENVIRONMENT = "production"
